### ISSUE TITLE
story/character disscusion

### ISSUE THREAD

**Issue by mattmanj17** [mattmanj17/Horizon#19]
improve story/ character backstory

**Comment by mattmanj17** [comment]
hmm ... this seams a little vague. what are the goals for this?

**Comment by Kurodius** [comment]
Make as good of a story as possible, that's it. We have enough concepts for the demo alone, but I would like to iron out and concept as much as possible to flesh out the story for the future. Not a high priority, but it could be a bit of fun.

**Comment by Kurodius** [comment]
story concepts doc
https://docs.google.com/document/d/18SeSgOBMwtaz4MQnJ0M_wCmxaGljkfhFte2wQoXlQkI/edit?usp=sharing
