### ISSUE TITLE
EVERYONE GO THROUGH THE FIRST THREE GIT VIDEOS

### ISSUE THREAD

**Issue by mattmanj17** [mattmanj17/Horizon#40]
DO IT

MAKE A GITHUB ACCOUNT

INSTALL SOURCETREE

MAKE YOUR OWN BRANCH

PUSH SOME COMMITS

MAKE A TEST PULL REQUEST

**Comment by Mneward** [comment]
So whoever has done this should probably make a small comment here saying they have done it.  I have done this.

**Comment by mattmanj17** [comment]
@Kurodius  , you did this right? could you leave a comment saying you did?

**Comment by mattmanj17** [comment]
ill close the issue once everyone has commented saying they have done the tutorial
