### ISSUE TITLE
Change working title

### ISSUE THREAD

**Issue by mattmanj17** [mattmanj17/Horizon#7]
there's a game coming out called Horizon: Zero Dawn https://www.youtube.com/watch?v=Fkg5UVTsKCE so we need a new name

**Comment by mattmanj17** [comment]
could we still use horizon as the "code name" for the project? it would be convenient to have a stable code name, for code naming purposes.

**Comment by mattmanj17** [comment]
Marco suggested Blazing frontier

**Comment by discwv** [comment]
Zenith Prime is the name now

**Comment by mattmanj17** [comment]
and the code name is project horizon
