### ISSUE TITLE
Unit movment is still buggy

### ISSUE THREAD

**Issue by mattmanj17** [mattmanj17/Horizon#85]
uggggggg............

**Comment by discwv** [comment]
hows it buggy?

**Comment by mattmanj17** [comment]
we can talk about it in the team meeting on monday (did you see us talking about that). I am about the send out an exe of the current version to the team, and you can see for your self.

to summarize, some times the game get confused about where a unit actually is, so it thinks squares that should be passable are not, sometimes the highlighting freekes out and you cant see the movment range at all (uggghhhhhh), and something i just noticed today, sometimes the AI makes moves for player characters. lol. bugs galore.

**Comment by mattmanj17** [comment]
i should probably break down all of those bugs into seperate issues. ohh, i should also make sure to tell people to log bugs they find as issues

**Comment by mattmanj17** [comment]
hmm ... i just realized something ... i think alot of these bugs might be caused by me not handling unit removal correctly. (at least the first bug)

**Comment by mattmanj17** [comment]
i should really make these into 3 issues

**Comment by mattmanj17** [comment]
break this into issues
