### ISSUE TITLE
Move different buttons and add other buttons

### ISSUE THREAD

**Issue by discwv** [mattmanj17/Horizon#99]
There was honestly a lot and i wasn't sure how to split it up. Its in the meeting notes here ( https://docs.google.com/document/d/1D4M0RGmwfTwXyv1nO63WxDLjf3_7xsVq7MyFXl7YETQ/edit?usp=sharing )

**Comment by mattmanj17** [comment]
ill go through the document some time  or have @Kurodius  do it, and make issues for everything.
